version: '3.7'

services:
    corp_calendar.fpm:
        container_name: corp_calendar.fpm
        env_file: .env
        build:
            context: docker/php-fpm
            dockerfile: Dockerfile
        working_dir: /var/www/corp_calendar
        restart: unless-stopped
        volumes:
            - ./:/var/www/corp_calendar
    corp_calendar.mysql:
        container_name: corp_calendar.mysql
        image: mysql:8
        env_file: .env
        restart: unless-stopped
        ports:
            - ${DOCKER_MYSQL_PORT}:3306
        volumes:
            - ./docker/mysql/data/:/var/lib/mysql/
        environment:
            MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DOCKER_MYSQL_DB}
            MYSQL_USER: ${DOCKER_MYSQL_USER}
            MYSQL_PASSWORD: ${DOCKER_MYSQL_PASSWORD}
    corp_calendar.nginx:
        container_name: corp_calendar.nginx
        image: nginx:latest
        env_file: .env
        restart: unless-stopped
        depends_on:
            - corp_calendar.fpm
            - corp_calendar.node
        ports:
            - ${DOCKER_NGINX_PORT}:80
        volumes:
            - ./:/var/www/corp_calendar
            - ./docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/sites-enabled:/etc/nginx/sites-enabled
    corp_calendar.node:
        container_name: corp_calendar.node
        volumes:
            - ./client:/var/www/corp_calendar
        working_dir: /var/www/corp_calendar
        entrypoint: sh -c "npm install && npm run build && npm run start"
        build:
            context: ./docker/node
            dockerfile: Dockerfile
        restart: unless-stopped

networks:
    default:
        name: corp_calendar
